export const REQUEST_ID_HEADER = 'x-request-id';

export const API_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  UNSUPPORTED_CHAIN: 'UNSUPPORTED_CHAIN',
  MARKET_NOT_FOUND: 'MARKET_NOT_FOUND',
  OUTCOME_NOT_FOUND: 'OUTCOME_NOT_FOUND',
  MARKET_NOT_TRADABLE: 'MARKET_NOT_TRADABLE',
  ORDERBOOK_UNAVAILABLE: 'ORDERBOOK_UNAVAILABLE',
  INSUFFICIENT_CASH: 'INSUFFICIENT_CASH',
  INVALID_TICK_SIZE: 'INVALID_TICK_SIZE',
  BELOW_MIN_ORDER_SIZE: 'BELOW_MIN_ORDER_SIZE',
  ORDER_PREVIEW_EXPIRED: 'ORDER_PREVIEW_EXPIRED',
  CAPABILITY_UNAVAILABLE: 'CAPABILITY_UNAVAILABLE',
  USER_REJECTED_SIGNATURE: 'USER_REJECTED_SIGNATURE',
  SIGNATURE_EXPIRED: 'SIGNATURE_EXPIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INFERENCE_FAILED: 'INFERENCE_FAILED',
  CACHE_ENTRY_EXPIRED: 'CACHE_ENTRY_EXPIRED',
  POLYMARKET_API_ERROR: 'POLYMARKET_API_ERROR',
} as const;
